version: '3.1'

services:

  postgres:
    image: postgres:10-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: demo
      POSTGRES_USER: demo
      POSTGRES_PASSWORD: demo

  tc-server:
    image: terracotta/terracotta-server-oss:5.6.4
    ports:
      - 9410:9410

