version: '3.1'

services:

  postgres:
    image: postgres:10-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: demo
      POSTGRES_USER: demo
      POSTGRES_PASSWORD: demo

  demo1:
    image: cache-demo
    ports:
      - 8081:8080
    environment:
      DB_HOST: postgres
      TC_HOST: tc-server
      CACHE_CONSISTENCY: REPL_SYNC
      ADDRESS_LIST: "demo1,demo2"
    depends_on:
      - postgres

  demo2:
    image: cache-demo
    ports:
      - 8082:8080
    environment:
      DB_HOST: postgres
      TC_HOST: tc-server
      CACHE_CONSISTENCY: REPL_SYNC
      ADDRESS_LIST: "demo1,demo2"
    depends_on:
      - postgres
